In [1]:
import numpy as np

# 2D vector space
v1 = np.array([1, 2])
v2 = np.array([3, 4])

# Vector addition
v3 = v1 + v2
print(v3)  # Output: [4, 6]

# Scalar multiplication
v4 = 2 * v1
print(v4)  # Output: [2, 4]

[4 6]
[2 4]


In [2]:
import numpy as np

def is_linearly_independent(vectors):
    matrix = np.column_stack(vectors)
    rank = np.linalg.matrix_rank(matrix)
    return rank == len(vectors)

# Example usage
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([2, 2])

vectors = [v1, v2, v3]
print(is_linearly_independent(vectors))  # Output: False

False


In [3]:
def is_linearly_independent(vectors):
    matrix = np.column_stack(vectors)
    rank = np.linalg.matrix_rank(matrix)
    return rank == len(vectors)

# Example usage
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([2, 2])

vectors = [v1, v2, v3]
print(is_linearly_independent(vectors))  # Output: False

False


In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
C = A + B
print(C)
# Output:
# [[6 8]
#  [10 12]]

# Matrix subtraction
D = A - B
print(D)
# Output:
# [[-4 -4]
#  [-4 -4]]

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Scalar multiplication
C = 2 * A
print(C)
# Output:
# [[2 4]
#  [6 8]]

# Matrix multiplication
D = np.dot(A, B)
print(D)
# Output:
# [[19 22]
#  [43 50]]

[[2 4]
 [6 8]]
[[19 22]
 [43 50]]


In [7]:
A = np.array([[2, 1], [1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
# Output: [3. 1.]

print("Eigenvectors:")
print(eigenvectors)
# Output:
# [[ 0.70710678 -0.70710678]
#  [ 0.70710678  0.70710678]]

Eigenvalues:
[3. 1.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [10]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Generate sample data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# Standardize the data
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

# Apply PCA
pca = PCA(n_components=1)
X_pca = pca.fit_transform(X_std)

print("Original Data:")
print(X)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

print("PCA-transformed Data:")
print(X_pca)
# Output:
# [[-1.8973666 ]
# [-0.63245553]
# [ 0.63245553]
# [ 1.8973666 ]]

Original Data:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
PCA-transformed Data:
[[-1.8973666 ]
 [-0.63245553]
 [ 0.63245553]
 [ 1.8973666 ]]


In [11]:
def rotation_matrix(theta):
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    return np.array([[cos_theta, -sin_theta], [sin_theta, cos_theta]])

def scaling_matrix(sx, sy):
    return np.array([[sx, 0], [0, sy]])

def shearing_matrix(kx, ky):
    return np.array([[1, kx], [ky, 1]])

# Example usage
v = np.array([1, 1])

# Rotation by 45 degrees
rotation = rotation_matrix(np.pi/4)
v_rotated = np.dot(rotation, v)
print("Rotated vector:", v_rotated)
# Rotated vector: [1.11022302e-16 1.41421356e+00]

# Scaling by 2 along x-axis and 3 along y-axis
scaling = scaling_matrix(2, 3)
v_scaled = np.dot(scaling, v)
print("Scaled vector:", v_scaled)
# Scaled vector: [2 3]

# Shearing by 1 along x-axis and 2 along y-axis
shearing = shearing_matrix(1, 2)
v_sheared = np.dot(shearing, v)
print("Sheared vector:", v_sheared)
# Sheared vector: [2 3]

Rotated vector: [1.11022302e-16 1.41421356e+00]
Scaled vector: [2 3]
Sheared vector: [2 3]


In [12]:
def gaussian_elimination(A, b):
    n = len(b)

    # Create the augmented matrix
    Ab = np.concatenate((A, b.reshape(n, 1)), axis=1)

    # Forward elimination
    for i in range(n):
        pivot = Ab[i][i]
        for j in range(i+1, n):
            factor = Ab[j][i] / pivot
            Ab[j] = Ab[j] - factor * Ab[i]

    # Back-substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (Ab[i][-1] - np.dot(Ab[i][:-1], x)) / Ab[i][i]

    return x

# Example usage
A = np.array([[2, 1], [1, 2]])
b = np.array([4, 5])

solution = gaussian_elimination(A, b)
print("Solution:", solution)

Solution: [0.5 3. ]
